### ISSUE TITLE
Anthropic(apiKey: <access token>) is not known per README doc.

### ISSUE THREAD

**Issue by UncleRic** [fumito-ito/AnthropicSwiftSDK#15]
Scenario: 1) I've added this Swift Package to my Xcode v15/Mac.
                 2) I've imported SwiftAnthropic
                 3) The 'Anthropic()' is unknown.
                 
                 
![Screenshot 2024-05-19 at 12 04 09 PM](https://github.com/fumito-ito/AnthropicSwiftSDK/assets/862735/76e8eaf2-972f-415a-a35a-22c87c726a6c)

**Comment by fumito-ito** [comment]
hi @UncleRic I created a test macOS app and was able to successfully call `Anthropic(apiKey:)`.

From your screenshot, the `import SwiftAnthropic` part looks wrong.
If you want to use this library, please import it using `import AnthropicSwiftSDK`.
