### ISSUE TITLE
Package downloads swiftlint and presents a scary dialog

### ISSUE THREAD

**Issue by hyperlink** [fumito-ito/AnthropicSwiftSDK#4]
Hi there!

I'm trying out your package and I noticed it downloads swiftlint as part of it.  Is this required to use this package?

Also there's this scary dialog in xcode:

<img width="265" alt="image" src="https://github.com/fumito-ito/AnthropicSwiftSDK/assets/133309/8c4b6be0-ae5b-4497-952a-ac878931b56c">

Thanks!

**Comment by fumito-ito** [comment]
hi @hyperlink, thanks your feedback. This dialog is safe but annoying. So I removed SwiftLint Plugin #5 . Please use 0.2.1 or later if you need.
