### ISSUE TITLE
read me examples don't work

### ISSUE THREAD

**Issue by misbell** [fumito-ito/AnthropicSwiftSDK#41]
I gave up after a couple of hours. I installed the dependency into my Xcode project, added the framework, imported the library into my contentView. Created my API key, added it to the code, but this failed every time:

let anthropic = Anthropic(apiKey: "YOUR_OWN_API_KEY")

let message = Message(role: .user, content: [.text("This is test text")])
let response = try await anthropic.messages.createMessage([message], maxTokens: 1024)

Invalid Request, replacement path not found.
Also on the next streaming example.

if the first two simple examples don't work, that's a problem.

Error: invalidRequestError
error: the replacement path doesn't exist: "/var/folders/ys/k34fssws6j1f16ngj8v26gk80000gn/T/swift-generated-sources/@__swiftmacro_11HelloClaude11ContentViewV5items33_4735AD49642E300F748EDA2BC5A74A9CLL5QueryfMa_.swift"
error: the replacement path doesn't exist: "/var/folders/ys/k34fssws6j1f16ngj8v26gk80000gn/T/swift-generated-sources/@__swiftmacro_11HelloClaude11ContentViewV5items33_4735AD49642E300F748EDA2BC5A74A9CLL5QueryfMa_.swift"
error: the replacement path doesn't exist: "/var/folders/ys/k34fssws6j1f16ngj8v26gk80000gn/T/swift-generated-sources/@__swiftmacro_11HelloClaude11ContentViewV5items33_4735AD49642E300F748EDA2BC5A74A9CLL5QueryfMa_.swift"

**Comment by misbell** [comment]
(tried it with 0.5.0 and 0.5.1)

**Comment by misbell** [comment]
turning off debug executable on the scheme got rid of the replacement path error, but it's still an invalid request.

<img width="1341" alt="Screenshot 2024-09-27 at 8 52 56 PM" src="https://github.com/user-attachments/assets/10e5e61d-85fc-4e48-b8b3-70009c96bcaa">

**Comment by fumito-ito** [comment]
Hi @misbell , Could you try [example project in this repository](https://github.com/fumito-ito/AnthropicSwiftSDK/tree/main/Example.swiftpm) ? The steps to try it are following.

1. clone this repository
2. move to project root
3. run `xed Example.swiftpm`
4. run example project and fill api key with yours.

**Comment by fumito-ito** [comment]
Hi @misbell . Thanks your reporting. The problem for `invalidRequest` is fixed. Please try https://github.com/fumito-ito/AnthropicSwiftSDK/releases/tag/0.5.2 .

**Comment by misbell** [comment]
Ok, I just tried the API with Python had succeeded. I'll try the new Swift API.

**Comment by misbell** [comment]
0.5.2 is returns a response as expected. thanks.
