### ISSUE TITLE
Streaming returns no content

### ISSUE THREAD

**Issue by misbell** [fumito-ito/AnthropicSwiftSDK#44]
Calling the streaming example, sending two messages, returns an empty content array.

<img width="1387" alt="Screenshot 2024-09-29 at 8 46 10 AM" src="https://github.com/user-attachments/assets/c98e0f19-1162-4723-b8dc-213cbfb01b5a">

**Comment by fumito-ito** [comment]
@misbell Yes. The `message_start event` contains a message object with empty content. For more details, please refer to https://docs.anthropic.com/en/api/messages-streaming#event-types.

If you want to handle content within the message stream, please use the `content_block_delta` event as shown below.

https://github.com/fumito-ito/AnthropicSwiftSDK/blob/e06503a170602762aa0f5fde220122a1c13e1dc3/Example.swiftpm/ViewModel/StreamViewModel.swift#L44-L66
