### ISSUE TITLE
Support computer use

### ISSUE THREAD

**Issue by fumito-ito** [fumito-ito/AnthropicSwiftSDK#49]
Refs: https://docs.anthropic.com/en/docs/build-with-claude/computer-use

**Comment by ptrkstr** [comment]
Thank you for this fantastic package @fumito-ito, using Macros in the [FunctionCalling](https://github.com/FunctionCalling/FunctionCalling) package for tools is also a very clever approach 😍 You library is by far the best Anthropic Swift SDK I have come across!

I've taken a look at Computer Use and looks like maybe a new Tool type needs to be introduced for Anthropic defined tools where it includes `type` (so only `type` and `name` are sent up). There would then be a challenge in declaring functions that exist but aren't encoded (given these are already defined Anthropic tools).

**Comment by fumito-ito** [comment]
@ptrkstr Thank you for your comment. As you pointed out, it is not possible to support the ComputerUse type while using the Tool in FunctionCalling. Therefore, I will take the following actions:

- Define entities within this SDK that correspond to Anthropic’s ToolUse and ComputerUse like #54.
- Remove the dependency on FunctionCalling and create a FunctionCalling extension specifically for AnthropicSwiftSDK, similar to [other extension libraries](https://github.com/FunctionCalling) of FunctionCalling.
    - Move the utility functions previously defined in AnthropicSwiftSDK to the above extension.

**Comment by ptrkstr** [comment]
Thank you for addressing this so quickly @fumito-ito 🙏 
Something also needed is being able to specify the computer use beta `computer-use-2024-10-22`.
Maybe the code could be updated to take in an array or option set of beta versions so it's possible to have:
```
anthropic-beta: "message-batches-2024-09-24,computer-use-2024-10-22"
```
